spring.application.name=apireservas

server.port=9090

# Servicio de canchas
spring.cloud.gateway.server.webmvc.routes[0].id=servicio-canchas
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/canchas/**

# Servicio de reservas
spring.cloud.gateway.server.webmvc.routes[1].id=servicio-reservas
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/reservas/**

# Servicio de usuarios
spring.cloud.gateway.server.webmvc.routes[2].id=servicio-usuarios
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/users,/api/users/**
